export {
  createParallelClient,
  type ParallelSearchRequest,
  type ParallelSearchResponse,
  type ParallelSearchResult,
  runParallelSearch,
  SEARCH_PROCESSORS,
  type SearchProcessor,
  searchRequestSchema,
  searchResponseSchema,
  searchResultSchema,
} from "@repo/parallel-core";
export {
  buildSearchCompletedSnapshot,
  buildSearchErrorSnapshot,
  buildSearchRunningSnapshot,
  createParallelSearchLifecycle,
  createParallelSearchPersistenceCallbacks,
  createParallelSearchPersistenceContext,
  createParallelSearchSnapshotAdapter,
  mapSearchResults,
  type ParallelSearchCompletedArgs,
  type ParallelSearchDomainAdapter,
  type ParallelSearchErroredArgs,
  type ParallelSearchLifecycle as ParallelSearchPersistenceLifecycle,
  type ParallelSearchLifecycleCallbacks,
  type ParallelSearchPersistenceOptions,
  type ParallelSearchResultsAdapter,
  type ParallelSearchSnapshotAdapter,
  type SearchResultRecord,
  type SearchStatus,
  type SearchTaskSnapshot,
  selectParallelSearchForClient,
} from "@repo/parallel-instantdb";
export {
  createParallelSearchTaskHooks,
  type ExecuteParallelSearchOptions,
  executeParallelSearch,
  type ParallelSearchLifecycle,
} from "@repo/parallel-trigger";
